import { Link } from 'react-router-dom'

export default function Privacy() {
  const effectiveDate = 'January 18, 2026'

  return (
    <div className="bg-black text-white">
      <div className="mx-auto max-w-4xl px-6 pb-24 pt-28 md:px-10 lg:px-16">
        <div className="mb-10">
          <p className="text-xs font-light tracking-tight text-white/60">Effective date: {effectiveDate}</p>
          <h1 className="mt-3 text-3xl font-extralight tracking-tight sm:text-4xl">Privacy Policy</h1>
          <p className="mt-4 text-sm font-light leading-relaxed text-white/65">
            This Privacy Policy explains how Adaptive Learning Agent (“we”, “us”) collects, uses, and protects
            information when you use the application.
          </p>
        </div>

        <div className="space-y-10">
          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">What we collect</h2>
            <ul className="space-y-2 text-sm font-light leading-relaxed text-white/65">
              <li>• Account information (such as name, email, authentication metadata) if you create an account.</li>
              <li>
                • Learning activity data generated by the app (detected topics, study sessions, roadmaps, schedules,
                quiz results, and progress/analytics).
              </li>
              <li>
                • Content you submit to the app (for example text extracted from OCR or notes you provide) to generate
                summaries, roadmaps, quizzes, and suggestions.
              </li>
              <li>• Basic technical data (device/browser metadata, timestamps, and diagnostic logs) for reliability.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Screen capture & OCR</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              The application may capture frames or screenshots from your screen/capture source to detect and extract
              learning content via OCR. The purpose is to identify topics and generate learning assistance.
            </p>
            <p className="text-sm font-light leading-relaxed text-white/65">
              You control when detection runs. If you disable detection, the app should stop capturing new frames.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">How we use information</h2>
            <ul className="space-y-2 text-sm font-light leading-relaxed text-white/65">
              <li>• Provide core features: topic detection, concept graphs, roadmaps, quizzes, timetables, analytics.</li>
              <li>• Improve accuracy and quality (debugging, performance monitoring, and feature refinement).</li>
              <li>• Protect the service (security monitoring, abuse prevention, and fraud detection).</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">AI / third-party processing</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              Some features use third-party AI providers (for example, an LLM) to generate summaries, explanations,
              quizzes, and roadmaps. When you use those features, relevant text (and only what is required to fulfill
              the request) may be sent to the provider.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Data retention</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              We retain data for as long as needed to provide the service and operate the application. Retention may
              vary by data type (e.g., cached summaries vs. user progress). If you request deletion, we will take
              reasonable steps to delete your account data, subject to technical and legal constraints.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Security</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              We apply reasonable technical safeguards to protect data, but no method of transmission or storage is
              100% secure.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Your choices</h2>
            <ul className="space-y-2 text-sm font-light leading-relaxed text-white/65">
              <li>• Start/stop detection at any time.</li>
              <li>• Review or delete learning data within the app where available.</li>
              <li>• Request account deletion if accounts are enabled in your deployment.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Contact</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              For privacy questions, contact your administrator or the team responsible for this deployment.
            </p>
          </section>

          <div className="pt-2">
            <Link
              to="/"
              className="inline-flex items-center rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-light text-white/80 transition-colors hover:bg-white/10"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
