import { Link } from 'react-router-dom'

export default function Terms() {
  const effectiveDate = 'January 18, 2026'

  return (
    <div className="bg-black text-white">
      <div className="mx-auto max-w-4xl px-6 pb-24 pt-28 md:px-10 lg:px-16">
        <div className="mb-10">
          <p className="text-xs font-light tracking-tight text-white/60">Effective date: {effectiveDate}</p>
          <h1 className="mt-3 text-3xl font-extralight tracking-tight sm:text-4xl">Terms of Service</h1>
          <p className="mt-4 text-sm font-light leading-relaxed text-white/65">
            These Terms govern your use of Adaptive Learning Agent. By using the application, you agree to these
            Terms.
          </p>
        </div>

        <div className="space-y-10">
          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Use of the app</h2>
            <ul className="space-y-2 text-sm font-light leading-relaxed text-white/65">
              <li>• Use the app only for lawful purposes.</li>
              <li>• Do not attempt to disrupt, reverse engineer, or abuse the service.</li>
              <li>• You are responsible for the content you provide to the app.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Screen content responsibility</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              If you enable detection, the app may process content visible in your capture source (e.g., text on your
              screen) for OCR and topic detection. You should not use detection on sensitive or confidential material
              unless you have permission.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">AI-generated outputs</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              Explanations, roadmaps, quizzes, and suggestions may be generated by AI and can be incorrect or
              incomplete. You are responsible for verifying outputs before relying on them.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Accounts</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              If accounts are enabled in your deployment, you are responsible for keeping your credentials secure.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Availability</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              We may change, suspend, or discontinue features at any time. We aim for reliable operation but do not
              guarantee uninterrupted service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Limitation of liability</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              To the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential
              damages arising from use of the app.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium tracking-tight">Changes</h2>
            <p className="text-sm font-light leading-relaxed text-white/65">
              We may update these Terms from time to time. Continued use after updates means you accept the updated
              Terms.
            </p>
          </section>

          <div className="pt-2">
            <Link
              to="/"
              className="inline-flex items-center rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-light text-white/80 transition-colors hover:bg-white/10"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
